def chart = api.newChartBuilder()
		.newScatter()
		.getOptions()
		.setHideLegend(false)
		.setHideTooltips(false)
		.setDisableDrilldown(false)
		.setDisableZoom(false)
		.setDiscretization(true)
		.setDisableGridDiscretization(false)
		.back()
		.addSeries()
		.setLabel('Series 1')
		.setDatamart('DM.Transaction')
		.setCurrency('EUR')
		.setAxisX('Quantity').withTotal().back()
		.setAxisY('Discount').withPercent().back()
		.setAggregationBy('CustomerId')
		.setBandBy('Region')
		.setShowBandByLegend(false)
		.addDimFilter('InvoiceDateYear', out.Year as String)
		.back()

		.getDictionary()
		.buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"∑Quantity","field":{"name":"Quantity","rank":5,"measureType":"EXTENDED","functionalType":"PERUNITBASIS","visibility":1,"source":"DMDS.Transaction","sourceField":"Quantity","expression":"Quantity","system":false,"deleted":false,"partitioningKey":false,"auxiliary":false,"deployed":true,"persisted":true,"dimension":false,"calculated":false,"aggregation":false,"time":false,"queryable":true,"numeric":true,"key":false,"type":"QUANTITY","owningFC":"Transaction","messages":{},"label":"Quantity"},"key":"x","keyLabel":"Axis X","sectionLabel":"Series 1","seriesIndex":0},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"∑Discount/ƒ{base} (%)","field":{"name":"Discount","rank":8,"measureType":"PERUNIT","visibility":1,"source":"DMDS.Transaction","sourceField":"Discount","expression":"Discount","system":false,"deleted":false,"partitioningKey":false,"auxiliary":false,"deployed":true,"persisted":true,"dimension":false,"calculated":false,"aggregation":false,"time":false,"queryable":true,"numeric":true,"key":false,"type":"MONEY","owningFC":"Transaction","messages":{},"label":"Discount"},"key":"y","keyLabel":"Axis Y","sectionLabel":"Series 1","seriesIndex":0},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"Customer Id","field":{"name":"CustomerId","rank":3,"visibility":1,"source":"DMDS.Transaction","sourceField":"CustomerId","expression":"CustomerId","system":false,"deleted":false,"dbTable":"DM_Transaction","dbColumn":"attribute8","partitioningKey":false,"auxiliary":false,"deployed":true,"persisted":true,"dimension":true,"calculated":false,"aggregation":false,"time":false,"queryable":true,"numeric":false,"key":false,"type":"TEXT","owningFC":"Transaction","messages":{},"label":"Customer Id"},"key":"groupBy","keyLabel":"Aggregation By","sectionLabel":"Series 1","seriesIndex":0},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"Region","field":{"name":"Region","rank":24,"visibility":1,"source":"DMDS.Customer","sourceField":"Region","expression":"Region","system":false,"deleted":false,"partitioningKey":false,"auxiliary":false,"deployed":true,"persisted":true,"dimension":true,"calculated":false,"aggregation":false,"time":false,"queryable":true,"numeric":false,"key":false,"type":"TEXT","owningFC":"Customer","messages":{},"label":"Region"},"key":"bandBy","keyLabel":"Band By","sectionLabel":"Series 1","seriesIndex":0}]')
		.back()
		.build()
return chart